### ISSUE TITLE
Does not sort IPv4 & IPv6 addresses anymore

### ISSUE THREAD

**Issue by mbunkus** [FyiurAmron/sortablejs#1]
Hey,

it seems like you've replaced the jQuery table sorter plugin with your own version. In the process you've unfortunately not implemented all the types that jQuery's implementation supported. For us sorting IPv4 and IPv6 addresses correctly is paramount, so this is a major regression for us. Please reconsider using jQuery again. Thanks.

**Comment by FyiurAmron** [comment]
@mbunkus for further reference: if you or anybody else needs support for a currently nonexistent feature (IPv6 sorting being one of them), please consider, as usual with OSS, writing the needed code and submitting a PR for it.
