### ISSUE TITLE
global variable declarations possibly break other plugins

### ISSUE THREAD

**Issue by FyiurAmron** [FyiurAmron/sortablejs#21]
They should be `var`-ed instead and turned local, instead of leaking to global scope. Makes it both easier to debug and safe for other JS code. Note that this should probably also include other autofixes for problems outlined by either http://www.jslint.com/ (strict) or http://www.jslint.com/ (transitional) JS linter, plus a proper pretty-print (note that DokuWiki minifies the script internally, so all and any minification attempt is totally not needed in here).

**Comment by oiv** [comment]
FyiurAmron The plugin is based on code from http://www.kryogenix.org/code/browser/sorttable/ I have no use for this plugin in my site anymore so this is why the development has slowed down a lot. (And it is quite old :D) 
Are you interested on adopting the code?

**Comment by FyiurAmron** [comment]
@oiv sure, I'll be actively using it for the months to come, so that wouldn't be a problem for me, as I'd have to make the patches anyway. As you can see on https://github.com/oiv/sortablejs/pull/26 , I've already fixed most of the things that were bothering me, and I'm looking forward to take a look at https://github.com/oiv/sortablejs/issues/4 & https://github.com/oiv/sortablejs/issues/9 next.

**Comment by oiv** [comment]
@FyiurAmron Can you please contact me on email. Could not find a way to find your contact info. I'm willing to handle this plugin to someone who has time for it.

**Comment by FyiurAmron** [comment]
@oiv Done. In case my mail hits your spambox for whatever reason, my address is vaxquis at gmail.com .

**Comment by FyiurAmron** [comment]
fixed in #26
