### ISSUE TITLE
Integration as code is not possible

### ISSUE THREAD

**Issue by paddy91** [FyiurAmron/sortablejs#32]
It is not possible to insert a sortable table into a code block between the code tag.

Version: 2017-02-19e "Frusterick Manners"

**Comment by FyiurAmron** [comment]
It's impossible to have a table in `<code>` as well, for the obvious reasons. Since code blocks are, by definition, preformatted and non-interactive, I don't see neither how or why this should work at all. Unless I'm missing something here, it's impossible by design and should stay that way.
