### ISSUE TITLE
Warning: Use of undefined constant DOKU_LEXER_ENTER

### ISSUE THREAD

**Issue by VinceT** [FyiurAmron/sortablejs#34]
Using PHP 7.4.2, I get this message : 

Warning: Use of undefined constant DOKU_LEXER_ENTER - assumed 'DOKU_LEXER_ENTER' (this will throw an Error in a future version of PHP) in K:\wamp\www\INRAwiki\lib\plugins\sortablejs\syntax.php on line 69

Refreshing the page clears the message.

**Comment by VinceT** [comment]
No answer since 2 months...

**Comment by FyiurAmron** [comment]
@VinceT sorry, but I'm doing pro bono service here, not a hotline. You're not on paid Amazon service, don't expect next-day delivery.

Also, you didn't provide any actual repro/debugging info for me to start from - just saying "using PHP 7.4.2" is seldom enough. At last an exact Dokuwiki version and runtime env info is needed to repro. `DOKU_LEXER_ENTER` is a valid const, defined in `inc/defines.php`. I have a `error_reporting  =  E_ALL & ~E_NOTICE & ~E_STRICT` set, and I don't get this.
