### ISSUE TITLE
Feature request - see forum entry: https://forum.dokuwiki.org/d/4975

### ISSUE THREAD

**Issue by Chris75forumname** [FyiurAmron/sortablejs#39]
Hi, I am looking for a plugin with Excel-like filter options for Tables, just like the one below!

http://www.javascriptkit.com/script/script2/tablefilter.shtml

There is actually a more recent website about this open source project by Max Guglielmi:

http://tablefilter.free.fr/

I checked out this demo page and I would opt for the dropdown menus with predefined filter entries above each collumn header. A working code example by the same author, which is exactly what I would like to use, is shown here:

https://codepen.io/koalyptus/pen/wKBOLp

Unfortunately, approximately 10 available table related Plugins in Dokuwiki do not offer this functionality. So, this feature request, even though more than 10 years old, is still urgent today! Is there any current work in progress? 

Thanks! Yours, Chris

**Comment by FyiurAmron** [comment]
@Chris75forumname sorry, this plugin is in maintenance mode. I don't use dokuwiki that much nowadays, and I'm swamped with other stuff. Pull Requests are welcome, though.
