### ISSUE TITLE
Sort has no effect when exported to PDF

### ISSUE THREAD

**Issue by grossmaul** [FyiurAmron/sortablejs#40]
Using the [DW2PDF](https://www.dokuwiki.org/plugin:dw2pdf) Plugin the table is not sorted in the PDF output.
Only the order is visible which is given in the source code of the page.

**Comment by FyiurAmron** [comment]
@grossmaul have you tried using Chrome's built-in PDF printer instead?

**Comment by grossmaul** [comment]
Thank you, but unfortunately Sam Wilson's plugin is not compatible with DW's newest release... and was not updated for years.

So I will stick with your plugin.

The print function works fine and prints the correct order (incl. PDF), but has no fancy stuff which is included in the DW2PDF plugin.

**Comment by FyiurAmron** [comment]
I'm closing since the requested feature/change is outside of current plugin scope.
