### ISSUE TITLE
conflict with dtable plugin

### ISSUE THREAD

**Issue by asheenlevrai** [FyiurAmron/sortablejs#41]
Hi :)

When right-clicking on a table after the order of the rows was reorganized via the [sortablejs plugin](https://www.dokuwiki.org/plugin:sortablejs), the editable row is not the one that was highlighted but rather another one.

My best guess is that [dtable](https://www.dokuwiki.org/plugin:dtable) edits the row that would correspond to the selected position if the rows of the table had not been sorted.

Best,
-a-

**Comment by FyiurAmron** [comment]
@asheenlevrai although cross-plugin compatibility is outside the scope of this repo. I've updated the README to highlight this. In short, it's impossible to make plugins compatible with each other if they're mutating the same data. In this case, both operations (table editing and table sorting) should be done in separate passes.

FWIW, I'd say this is simply hard-next-to-impossible to fix on sortable side, so https://github.com/gkrid/dokuwiki-plugin-dtable/issues/15 is your best bet here (although I suspect you might get a similar response there).

**Comment by asheenlevrai** [comment]
I understand.
Thanks
