### ISSUE TITLE
PHP 8.x Warning

### ISSUE THREAD

**Issue by LMS235** [FyiurAmron/sortablejs#44]
...
`Got error 'PHP message: PHP Warning:  Undefined array key 1 in /.../lib/plugins/sortablejs/syntax.php on line 110`
...

**Comment by FyiurAmron** [comment]
@LMS235 should be fixed by [fa94c83](https://github.com/FyiurAmron/sortablejs/commit/fa94c836fb4e3d67d4af69947ac1efe81364eb3d) , please verify if it works for you.

**Comment by LMS235** [comment]
Hi, testet the code, no errors
